/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NewRMS;

//import static NewRMS.Replica1.replicaId;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.net.Socket;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class ReplicaCreator extends javax.swing.JFrame {
final File fileToSend[]=new File[1];
 static int replicaId;
    /**
     * Creates new form ReplicaCreator
     */
    public ReplicaCreator() {
        initComponents();
        this.setLocationRelativeTo(null);
         Toolkit tk = getToolkit();
         Dimension size= tk.getScreenSize();
         setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
         //setSize(800,800);
         scaleImage();
    }
     public void scaleImage(){
    ImageIcon icon = new ImageIcon("C:\\Users\\Hp\\Downloads\\6.jpg");
    Image img= icon.getImage();
    Image imgScale =img.getScaledInstance(jLabel3.getWidth(),jLabel3.getHeight(), Image.SCALE_SMOOTH);
   
    ImageIcon scaledIcon = new ImageIcon(imgScale);
    jLabel3.setIcon(scaledIcon);
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fileName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        chooseFile = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        displayReplicaRecord = new javax.swing.JButton();
        createReplica = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Replica Creator");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153)));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 260, 44));

        fileName.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        fileName.setForeground(new java.awt.Color(255, 153, 153));
        fileName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fileName.setText("choose file to create replica");
        fileName.setToolTipText("");
        fileName.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(fileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 160, 530, 38));

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 153));
        jLabel2.setText("Enter Replica ServerIP");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 270, 42));

        chooseFile.setBackground(new java.awt.Color(246, 208, 242));
        chooseFile.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        chooseFile.setForeground(new java.awt.Color(0, 204, 204));
        chooseFile.setText("choose file");
        chooseFile.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        chooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFileActionPerformed(evt);
            }
        });
        jPanel1.add(chooseFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 224, 46));

        logout.setBackground(new java.awt.Color(246, 208, 242));
        logout.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(0, 204, 204));
        logout.setText("Logout");
        logout.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 200, 48));

        displayReplicaRecord.setBackground(new java.awt.Color(246, 208, 242));
        displayReplicaRecord.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        displayReplicaRecord.setForeground(new java.awt.Color(0, 204, 204));
        displayReplicaRecord.setText("Display Replica Record");
        displayReplicaRecord.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        displayReplicaRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayReplicaRecordActionPerformed(evt);
            }
        });
        jPanel1.add(displayReplicaRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 270, 48));

        createReplica.setBackground(new java.awt.Color(246, 208, 242));
        createReplica.setFont(new java.awt.Font("Lucida Calligraphy", 3, 18)); // NOI18N
        createReplica.setForeground(new java.awt.Color(0, 204, 204));
        createReplica.setText("Create Replica");
        createReplica.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        createReplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createReplicaActionPerformed(evt);
            }
        });
        jPanel1.add(createReplica, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 200, 46));

        jTextField1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 153, 153));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 310, 34));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 900, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFileActionPerformed
       JFileChooser jFileChooser = new JFileChooser();
                // Set the title of the dialog.
                jFileChooser.setDialogTitle("Choose a file to send.");
                // Show the dialog and if a file is chosen from the file chooser execute the following statements.
                if (jFileChooser.showOpenDialog(null)  == JFileChooser.APPROVE_OPTION) {
                    // Get the selected file.
                    fileToSend[0] = jFileChooser.getSelectedFile();
                    // Change the text of the java swing label to have the file name.
                    fileName.setText("The file you want to send is: " + fileToSend[0].getName());        
    }                           
    }//GEN-LAST:event_chooseFileActionPerformed

    private void createReplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createReplicaActionPerformed
         if (fileToSend[0] == null) {
                    fileName.setText("Please choose a file to send first!");
                    
                }
               else
               {
                    
                try
                 {
                    
                     String server1=jTextField1.getText();
                    
              FileInputStream fileInputStream = new FileInputStream(fileToSend[0].getAbsolutePath());
              Socket socket = new Socket(server1, 1234);
              DataOutputStream dataOutputStream = new DataOutputStream(socket.getOutputStream());
              String fileName = fileToSend[0].getName();
              byte[] fileNameBytes = fileName.getBytes();
              byte[] fileBytes = new byte[(int)fileToSend[0].length()];
              fileInputStream.read(fileBytes);
              dataOutputStream.writeInt(fileNameBytes.length);
              dataOutputStream.write(fileNameBytes);
              dataOutputStream.writeInt(fileBytes.length);
              int replicaSize=fileBytes.length;
              dataOutputStream.write(fileBytes);
              
              Class.forName("com.mysql.jdbc.Driver");
              java.sql.Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3308/rms","root","");
              String sql="insert into replica_record values(?,?,?,?,?,?)";
              java.util.Date date=new java.util.Date();
              java.sql.Date sqlDate=new java.sql.Date(date.getTime());
              java.sql.Timestamp sqlTime=new java.sql.Timestamp(date.getTime());
              PreparedStatement preparedStatement=(PreparedStatement)conn.prepareStatement(sql);
              preparedStatement.setInt(1,replicaId);
              preparedStatement.setString(2,fileName);
              preparedStatement.setString(3,server1);
              preparedStatement.setDate(4,sqlDate);
              preparedStatement.setTimestamp(5,sqlTime);
            
              preparedStatement.setInt(6,replicaSize);
              
              
                 int i= preparedStatement.executeUpdate();
             if(i!=0)
             {
             JOptionPane.showMessageDialog(null,"replica record updated");
            replicaId++;
             }
               }
               catch(Exception e)
           
               {
               e.printStackTrace();
               }
               }

    }//GEN-LAST:event_createReplicaActionPerformed

    private void displayReplicaRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayReplicaRecordActionPerformed
         ReplicaRecord rr=new ReplicaRecord();
        rr.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_displayReplicaRecordActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int a=JOptionPane.showConfirmDialog(logout,"Are You sure you want to logout");
     if(a==JOptionPane.YES_OPTION)
      {
         dispose();
         loginForm l=new loginForm();
        l.setVisible(true);
      }
    
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReplicaCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReplicaCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReplicaCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReplicaCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReplicaCreator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseFile;
    private javax.swing.JButton createReplica;
    private javax.swing.JButton displayReplicaRecord;
    private javax.swing.JLabel fileName;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
